#!/usr/bin/env bash

main(){
  TMPDIR=$(mktemp -d)

  cp --recursive --preserve=timestamps --backup --suffix=.pacnew rootfs/* ${TMPDIR}/
  env -i pacstrap -c -d -G -M ${TMPDIR} $(cat packages)
  test -d pkg || git clone https://github.com/btwiuse/archpkg pkg
  cp -v users groups pkg/*.pkg.tar.xz ${TMPDIR}/root/
  mount --bind ${TMPDIR} ${TMPDIR}

  cat inchroot.sh | arch-chroot ${TMPDIR} bash
  cat strap.sh | arch-chroot ${TMPDIR} env TERM=screen bash

  umount ${TMPDIR}
  tar --numeric-owner --xattrs --acls --exclude-from=exclude -C ${TMPDIR} -c . | docker import --change 'CMD ["/usr/bin/bash"]' --change 'ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 TZ=Asia/Shanghai' - latestarch/linux:latest
  rm -rf ${TMPDIR}
}

main "$@"
