#!/usr/bin/env bash

main(){
  TMPDIR=$(mktemp -d)

  # 0x00
  # from scratch
  # arch-bootstrap?
  # env -i pacstrap -c -d -G -M ${TMPDIR} $(./packages all) |& ts -s '%M:%S [pacstrap]'
  # sudo ./arch-bootstrap -q -d cache -a $ARCH
  {
  local newroot=$TMPDIR
  local DEST=$TMPDIR
  printf 'Creating install root at %s' "$newroot"
  mkdir -m 0755 -p "$newroot"/var/{cache/pacman/pkg,lib/pacman,log} "$newroot"/{dev,run,etc/pacman.d}
  mkdir -m 1777 -p "$newroot"/tmp
  mkdir -m 0555 -p "$newroot"/{sys,proc}
  test -e "$DEST/dev/null" || mknod "$DEST/dev/null" c 1 3
  test -e "$DEST/dev/random" || mknod -m 0644 "$DEST/dev/random" c 1 8
  test -e "$DEST/dev/urandom" || mknod -m 0644 "$DEST/dev/urandom" c 1 9
  env LC_ALL=C pacman --arch ${ARCH:=x86_64} -r "${TMPDIR}" -Sy $(./packages lite) --cachedir=cache --noconfirm --config=rootfs/etc/pacman-bootstrap.conf --overwrite '/*'
  } |& ts -s '%M:%S [pacstrap]'

  # 0x01
  # custom configurations
  cp --recursive --preserve=timestamps --backup --suffix=.pacold rootfs/* ${TMPDIR}/

  # 0x02
  # --install binpkg in chroot-- 
  # can we do without this in the future?
  # todo: multiarch: x86, armv7, aarch64
  # idea: manage personal configs with package hooks, like locale-en_xx
  # managing arch linux with meta packages
  # https://disconnected.systems/blog/archlinux-meta-packages/    -> btw the theme is great for cheat.sh frontend!!!
  # meta package name: btwiuse
  # may be make store some ebooks ...
  # classic ebooks ...
  sudo mkdir -p ${TMPDIR}/root/arch
  mount --bind ${PWD} ${TMPDIR}/root/arch
  cat inchroot.sh | arch-chroot ${TMPDIR} bash |& ts -s '%M:%S [inchroot]'
  umount ${TMPDIR}/root/arch

  # 0x03
  # docker import
  /bin/time -f '%e' -- tar --numeric-owner --xattrs --acls --exclude-from=exclude -C ${TMPDIR} -c . | docker import \
  --change 'ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US:en TERM=screen TZ=Asia/Shanghai' \
  --change 'USER btwiuse' \
  --change 'WORKDIR /home/btwiuse' \
  --change 'CMD ["/usr/bin/bash"]' \
  - latestarch/linux:latest

  # 0x04
  # cleanup
  rm -rf ${TMPDIR}
}

main "$@"

