#!/usr/bin/env bash

main(){
  TMPDIR=$(mktemp -d)

  # 0x00
  # from scratch
  env -i pacstrap -c -d -G -M ${TMPDIR} $(./packages all) |& ts -s '%M:%S [pacstrap]'

  # 0x01
  # custom configurations
  cp --recursive --preserve=timestamps --backup --suffix=.pacold rootfs/* ${TMPDIR}/

  # 0x02
  # --install binpkg in chroot-- 
  # can we do without this in the future?
  # todo: multiarch: x86, armv7, aarch64
  sudo mkdir -p ${TMPDIR}/root/arch
  mount --bind ${PWD} ${TMPDIR}/root/arch
  cat inchroot.sh | arch-chroot ${TMPDIR} bash |& ts -s '%M:%S [inchroot]'
  umount ${TMPDIR}/root/arch

  # 0x03
  # docker import
  /bin/time -f '%e' -- tar --numeric-owner --xattrs --acls --exclude-from=exclude -C ${TMPDIR} -c . | docker import \
  --change 'ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US:en TERM=screen TZ=Asia/Shanghai' \
  --change 'USER btwiuse' \
  --change 'WORKDIR /home/btwiuse' \
  --change 'CMD ["/usr/bin/bash"]' \
  - latestarch/linux:latest

  # 0x04
  # cleanup
  rm -rf ${TMPDIR}
}

main "$@"

