#!/usr/bin/env bash
git config user.name navigaid
git config user.email navigaid@gmail.com
#upstream=$(git rev-parse --abbrev-ref master@{upstream} | cut -d / -f 1)
#git remote set-url "$upstream" https://github.com/btwiuse/arch.git
[[ -d qemu-static ]] || git clone -b master https://github.com/btwiuse/qemu-static.git

