#!/usr/bin/env bash

all(){
  cd pkgs
  ls -1 | xargs cat
}

bare(){
  cat pkgs/bare
}

lite(){
  cd pkgs
  ls -1 | grep -v ^optional | xargs cat
}

main(){
  case $1 in
  bare)
    bare
  ;;
  lite)
    lite
  ;;
  *)
    all
  ;;
  esac
}

main "$@"
