#!/usr/bin/env bash

base(){
  cd pkgs
  cat base* base-devel dev keyring
}

all(){
  cd pkgs
  ls -1 | xargs cat
}

lite(){
  cd pkgs
  ls -1 | grep -v ^optional | xargs cat
}

main(){
  case $1 in
  base)
    base
  ;;
  lite)
    lite
  ;;
  *)
    all
  ;;
  esac
}

main "$@" | grep -v '#' | grep . | sort -u
