#!/usr/bin/env bash

set -eo pipefail

stage1(){
  env LC_ALL=C pacstrap -C rootfs/etc/pacman-bootstrap-${ARCH}.conf -c -d -G -M ${TMPDIR} $(./packages bootstrap)
}

stage2(){
  sudo mkdir -p ${TMPDIR}/root/arch
  sudo mkdir -p ${TMPDIR}/var/cache/pacman/pkg
  mount --bind ${PWD} ${TMPDIR}/root/arch
  # propagate host cache from stage1 to stage2
  mount --bind {,${TMPDIR}}/var/cache/pacman/pkg
  arch-chroot ${TMPDIR} env LC_ALL=C VARIANT=${VARIANT} ARCH=${ARCH} bash <<- 'END_OF_STAGE2'
	#!/usr/bin/env bash

	set -e

	# should be default hook
	# redundant when ./update
	gen-locale(){
	  locale-gen en_US.UTF-8
	}

	# common to ./update and from-scratch build
	# todo: https://www.archlinux.org/todo/switch-to-systemd-sysusers/
	ug(){
	  # TODO: try chpasswd

	  for user in $(cat users); do
	    useradd -U -ms /bin/bash ${user} && passwd -d ${user}
	  done

	  for group in $(cat groups); do
	    groupadd -f ${group}
	    for user in $(cat users); do
	      usermod -a -G ${group} ${user}
	    done
	  done

	  echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/wheel
	}

	# should be default hook
	# redundant when ./update
	setup-keyring(){
	  # pacman-key --init && pacman-key --populate archlinux blackarch
	  # x86
	  pacman-key --init && pacman-key --populate $(./keyrings)
	}

	# should be default hook
	update-packages(){
	# mainly used to update existing packages when you run ./update
	# redundant when you build from scratch
	# --cachedir=/root/arch/cache-${ARCH} 
	./packages base | xargs pacman -Syu --needed --noconfirm --overwrite '/*'
	# should be default hook
	# redundant when ./update
	# pkgfile --update
	}

	stage2(){
	  # chroot defaults to /
	  cd /root/arch
	  # order matters here, you need sudo installed to setup sudoers...
	  update-packages
	  gen-locale
	  ug
	  setup-keyring
	}

	stage2 "$@"
END_OF_STAGE2
  umount ${TMPDIR}/var/cache/pacman/pkg
  umount ${TMPDIR}/root/arch
}

stage3(){
  IMAGE=latestarch/linux:${VARIANT}-${ARCH}
  echo "building $IMAGE ..."
  /bin/time -f '%e' -- tar --numeric-owner --xattrs --acls --exclude-from=exclude -C ${TMPDIR} -c . | docker import \
  --change 'ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US:en TERM=screen TZ=Asia/Shanghai' \
  --change 'USER btwiuse' \
  --change 'WORKDIR /home/btwiuse' \
  --change 'CMD ["/usr/bin/bash"]' \
  - $IMAGE
  echo "Your image is ready!"
  echo "docker run -it $IMAGE"
}

main(){
  TMPDIR=$(mktemp -d)

  # 0x00
  # from scratch
  if [[ -z $ARCH ]]; then exit 1; fi
  printf 'Bootstrapping btwiuse/arch:%s\n' "$ARCH"
  stage1 |& ts -s "stage1]"

  # 0x01
  # custom configurations
  cp --recursive --preserve=timestamps --backup --suffix=.pacold rootfs/* ${TMPDIR}/
  ln -sf pacman-${ARCH}.conf ${TMPDIR}/etc/pacman.conf

  # 0x02
  # idea: manage personal configs with package hooks, like locale-en_xx
  # managing arch linux with meta packages
  # https://disconnected.systems/blog/archlinux-meta-packages/    -> btw the theme is great for cheat.sh frontend!!!
  # meta package name: btwiuse
  # may be make store some ebooks ...
  # classic ebooks ...
  stage2 |& ts -s "stage2]"

  # 0x03
  # docker import
  stage3 |& ts -s "stage3]"

  # 0x04
  # cleanup
  rm -rf ${TMPDIR}
}

main "$@" |& ts -s "%M:%S [${ARCH}:"
