#!/usr/bin/env bash

set -e

# should be default hook
# redundant when ./update
gen-locale(){
  locale-gen en_US.UTF-8
}

# common to ./update and from-scratch build
# todo: https://www.archlinux.org/todo/switch-to-systemd-sysusers/
ug(){
  # TODO: try chpasswd

  for user in $(cat users); do
    useradd -U -ms /bin/bash ${user} && passwd -d ${user}
  done

  for group in $(cat groups); do
    groupadd -f ${group}
    for user in $(cat users); do
      usermod -a -G ${group} ${user}
    done
  done

  echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/wheel
}

# should be default hook
# redundant when ./update
setup-keyring(){
  # pacman-key --init && pacman-key --populate archlinux blackarch
  # x86
  pacman-key --init && pacman-key --populate $(./keyrings)
}

# should be default hook
update-packages(){
# mainly used to update existing packages when you run ./update
# redundant when you build from scratch
# --cachedir=/root/arch/cache-${ARCH} 
./packages base | xargs pacman -Syu --noconfirm --overwrite '/*'
# should be default hook
# redundant when ./update
# pkgfile --update
}

stage2(){
  # chroot defaults to /
  cd /root/arch
  gen-locale
  ug
  setup-keyring
  update-packages
}

stage2 "$@"
