#!/usr/bin/env bash

set -e

stage1(){
  TMPDIR=$(mktemp -d)

  # 0x00
  # from scratch
  if [[ -z $ARCH ]]; then exit 1; fi
  printf 'Bootstrapping btwiuse/arch:%s\n' "$ARCH"
  env LC_ALL=C pacstrap -C rootfs/etc/pacman-bootstrap-${ARCH}.conf -c -d -G -M ${TMPDIR} $(./packages bootstrap) |& ts -s "%M:%S [${ARCH}::stage1/2]"

  # 0x01
  # custom configurations
  cp --recursive --preserve=timestamps --backup --suffix=.pacold rootfs/* ${TMPDIR}/
  ln -sf pacman-${ARCH}.conf ${TMPDIR}/etc/pacman.conf

  # 0x02
  # idea: manage personal configs with package hooks, like locale-en_xx
  # managing arch linux with meta packages
  # https://disconnected.systems/blog/archlinux-meta-packages/    -> btw the theme is great for cheat.sh frontend!!!
  # meta package name: btwiuse
  # may be make store some ebooks ...
  # classic ebooks ...
  sudo mkdir -p ${TMPDIR}/root/arch
  sudo mkdir -p ${TMPDIR}/var/cache/pacman/pkg
  mount --bind ${PWD} ${TMPDIR}/root/arch
  # propagate host cache from stage1 to stage2
  mount --bind {,${TMPDIR}}/var/cache/pacman/pkg
  cat stage2 | arch-chroot ${TMPDIR} env LC_ALL=C ARCH=${ARCH} bash |& ts -s "%M:%S [${ARCH}::stage2/2]"
  umount ${TMPDIR}/var/cache/pacman/pkg
  umount ${TMPDIR}/root/arch

  # 0x03
  # docker import
  IMAGE=latestarch/linux:${VARIANT}-${ARCH}
  echo "building $IMAGE ..."
  /bin/time -f '%e' -- tar --numeric-owner --xattrs --acls --exclude-from=exclude -C ${TMPDIR} -c . | docker import \
  --change 'ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US:en TERM=screen TZ=Asia/Shanghai' \
  --change 'USER btwiuse' \
  --change 'WORKDIR /home/btwiuse' \
  --change 'CMD ["/usr/bin/bash"]' \
  - $IMAGE
  echo "Your image is ready!"
  echo "docker run -it $IMAGE"

  # 0x04
  # cleanup
  rm -rf ${TMPDIR}
}

stage1 "$@"
