[options]
HoldPkg     = pacman glibc
Architecture = x86_64
ILoveCandy
Color
VerbosePkgLists
SigLevel = Never TrustAll

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist


#[multilib]
#Include = /etc/pacman.d/mirrorlist

[archlinuxcn]
Server = http://mirrors.ustc.edu.cn/archlinuxcn/$arch
Server = http://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch

[blackarch]
Server = http://mirrors.ustc.edu.cn/blackarch/$repo/os/$arch
Server = http://mirrors.tuna.tsinghua.edu.cn/blackarch/$repo/os/$arch

[btwiuse]
Server = https://github.com/btwiuse/archpkg/releases/download/current/
