[options]
HoldPkg     = pacman glibc
Architecture = armv7h
ILoveCandy
Color
VerbosePkgLists
SigLevel = Never TrustAll

[core]
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo

[extra]
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo

[community]
Server = http://ca.us.mirror.archlinuxarm.org/$arch/$repo

#[archlinuxcn]
#Server = http://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
#Server = http://mirrors.ustc.edu.cn/archlinuxcn/$arch

#[btwiuse]
#Server = https://github.com/btwiuse/archpkg/releases/download/current/
