[archlinuxcn]
Server = http://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
Server = http://mirrors.ustc.edu.cn/blackarch/archlinuxcn/$arch

[blackarch]
#Server = http://mirrors.ustc.edu.cn/blackarch/$repo/os/$arch
#Server = https://mirrors.ustc.edu.cn/blackarch/$repo/os/$arch
#Server = http://mirrors.tuna.tsinghua.edu.cn/blackarch/$repo/os/$arch
Server = http://mirrors.tuna.tsinghua.edu.cn/blackarch/$repo/os/$arch
Server = http://mirrors.ustc.edu.cn/blackarch/$repo/os/$arch

[btwiuse]
Server = https://github.com/btwiuse/archpkg/releases/download/current/
SigLevel = Never TrustAll
