#!/usr/bin/env bash

echo "------ HOOK START - BUILD -------"

getenforce

cat /proc/cmdline

printenv

docker images

whoami

pwd

df -h

ls -la

git status

lscpu

lsblk

lsmod

mount

free -h

ifconfig -a

# sudo make rootfs

sudo=sudo
if [[ $(whoami) = root ]]; then
  sudo=""
# else
# if ! which sudo; then
#   apt update && apt install -y sudo || :
# fi
fi

$sudo modprobe ext4 || :

# docker pull index.docker.io/latestarch/linux:latest
# $sudo docker pull ${IMAGE_NAME:-latestarch/linux} || :

if [[ -d /var/cache/pacman/pkg ]]; then
  PKGDIR=/var/cache/pacman/pkg
fi

$sudo docker run -v $PWD:$PWD -v /var/run:/var/run -v $PWD/rootfs/etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist -w $PWD --privileged -v ${PKGDIR:-$PWD/cache}:/var/cache/pacman/pkg ${IMAGE_NAME:-latestarch/linux} bash rootfs2docker

# $sudo docker build -t ${IMAGE_NAME:-latestarch/linux} .

echo "------ HOOK END - BUILD -------"
