#!/usr/bin/env bash

is_stdin_a_tty(){ [[ -t 0 ]] ;}

update_docker_image(){
  sudo=sudo
  if [[ $(whoami) = root ]]; then
    sudo=""
  fi

  # if host_arch == guest_arch == amd64 && host.is_arch()
  if [[ $(uname -m) = "${ARCH:=$(uname -m)}" ]] && [[ -d /var/cache/pacman/pkg ]]; then
    PKGDIR=/var/cache/pacman/pkg
  else
    PKGDIR="$PWD/cache-${ARCH}"
  fi

# -v $PWD/rootfs/etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist \
# -v $PWD/rootfs/etc/pacman.conf:/etc/pacman.conf \
  $sudo docker \
  run "$([[ -t 0 ]] && echo -it)" \
  -u root \
  -v "$PWD:$PWD" \
  -e "ARCH=${ARCH}" \
  -e "PKGDIR=${PKGDIR}" \
  -e "DOCKER_API_VERSION=1.44" \
  -e "VARIANT=${VARIANT:-base}" \
  -w "$PWD" \
  -v /var/run:/var/run \
  -v "${PKGDIR}:/var/cache/pacman/pkg" \
  --privileged \
  --net=host \
  btwiuse/arch:docker-x86_64 \
  ./stages
}

main(){
  echo "------ HOOK START - BUILD -------"
  update_docker_image
  echo "------ HOOK END - BUILD -------"
}

main "$@"
