#!/usr/bin/env bash

gather_info(){
  getenforce

  cat /proc/cmdline

  printenv

  docker images

  whoami

  pwd

  df -h

  ls -la

  git status

  lscpu

  lsblk

  lsmod

  mount

  free -h

  # ifconfig -a
}

is_stdin_a_tty(){ [[ -t 0 ]] ;}

update_docker_image(){
  sudo=sudo
  if [[ $(whoami) = root ]]; then
    sudo=""
  fi

  # if host_arch == guest_arch == amd64 && host.is_arch()
  if [[ $(uname -m) = ${ARCH:=$(uname -m)} ]] && [[ -d /var/cache/pacman/pkg ]]; then
    PKGDIR=/var/cache/pacman/pkg
  fi

# -v $PWD/rootfs/etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist \
# -v $PWD/rootfs/etc/pacman.conf:/etc/pacman.conf \
  $sudo docker \
  run $([[ -t 0 ]] && echo -it) \
  -u root \
  -v $PWD:$PWD \
  -e ARCH=${ARCH} \
  -e VARIANT=${VARIANT:-base} \
  -w $PWD \
  -v /var/run:/var/run \
  -v ${PKGDIR:-$PWD/cache-${ARCH}}:/var/cache/pacman/pkg \
  --privileged \
  --net=host \
  latestarch/linux:docker-${ARCH} \
  ./stages
}

main(){
  echo "------ HOOK START - BUILD -------"
# gather_info
  update_docker_image
  echo "------ HOOK END - BUILD -------"
}

main "$@"
