#!/usr/bin/env bash

gather_info(){
  getenforce

  cat /proc/cmdline

  printenv

  docker images

  whoami

  pwd

  df -h

  ls -la

  git status

  lscpu

  lsblk

  lsmod

  mount

  free -h

  # ifconfig -a
}

