#!/usr/bin/env bash

docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:latest

echo "------ HOOK END - POST_PUSH -------"

# trigger another build, causing an infinite autobuild loop
# btwiuse/arch self trigger
curl -X POST 'https://hub.docker.com/api/build/v1/source/94a2751c-5ddf-46ba-9223-6e78f2c925a1/trigger/18867be7-a54b-44a4-a7da-d97d3935ac3c/call/'
